"""Full-state backup / restore — the beta safety net.

Exports every table (in FK-dependency order) to a single JSON snapshot, so the
real pain of a data loss — months of expenses, goal progress, timeline,
relationships, settings — is recoverable, not just the login. Restore is
idempotent (``ON CONFLICT DO NOTHING``) and preserves primary keys + the user
password hash, so people log back in unchanged and all their data relinks.

Reference data (currencies, exchange rates) is excluded: it is regenerated by
the seeds on startup, so it never needs to live in a user backup.

Generic by design — it walks ``Base.metadata.sorted_tables``, so a table can
never be forgotten as the schema grows. The restore path is a no-auth CLI
(`python -m app.scripts.backup`) because after a wipe there is no developer
account to authenticate an API call.
"""

from __future__ import annotations

import json
import uuid
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession

import app.models  # noqa: F401 — registers every table on Base.metadata (the CLI
#                     entry point doesn't import models otherwise → empty snapshot)
from app.core.config import settings
from app.db.base import Base

SNAPSHOT_VERSION = 1
# Regenerated by the seeds — no need to carry it in a user backup.
_EXCLUDE = {"currencies", "exchange_rates", "alembic_version"}


def backup_dir() -> Path:
    if settings.BACKUP_DIR:
        return Path(settings.BACKUP_DIR)
    # app/services/backup_service.py → backend/backups
    return Path(__file__).resolve().parent.parent.parent / "backups"


def _encode(value: object) -> object:
    if isinstance(value, uuid.UUID):
        return str(value)
    if isinstance(value, Decimal):
        return str(value)
    if isinstance(value, datetime):   # before date — datetime is a subclass of date
        return value.isoformat()
    if isinstance(value, date):
        return value.isoformat()
    return value  # None / bool / int / float / str / dict / list (JSON columns)


def _decode(column, value: object) -> object:
    if value is None or isinstance(value, (dict, list)):
        return value
    try:
        pytype = column.type.python_type
    except Exception:  # noqa: BLE001 — some types don't implement python_type
        return value
    if pytype is uuid.UUID and isinstance(value, str):
        return uuid.UUID(value)
    if pytype is Decimal and isinstance(value, str):
        return Decimal(value)
    if pytype is datetime and isinstance(value, str):
        return datetime.fromisoformat(value)
    if pytype is date and isinstance(value, str):   # Date (not DateTime — that maps to datetime)
        return date.fromisoformat(value)
    return value


def _tables():
    """All model tables in FK-dependency order, minus regenerable reference data."""
    return [t for t in Base.metadata.sorted_tables if t.name not in _EXCLUDE]


async def export_state(db: AsyncSession) -> dict:
    """A JSON-serializable snapshot of every user-data table."""
    tables: dict[str, list[dict]] = {}
    for table in _tables():
        rows = (await db.execute(select(table))).mappings().all()
        tables[table.name] = [{k: _encode(v) for k, v in row.items()} for row in rows]
    return {
        "version": SNAPSHOT_VERSION,
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "tables": tables,
    }


async def import_state(db: AsyncSession, snapshot: dict) -> dict[str, int]:
    """Insert a snapshot's rows, skipping anything that already exists (by any
    conflict). Parents are inserted before children (sorted_tables order), so
    foreign keys always resolve. Returns rows inserted per table."""
    data = snapshot.get("tables", {})
    inserted: dict[str, int] = {}
    for table in _tables():
        rows = data.get(table.name, [])
        if not rows:
            continue
        count = 0
        cols = {c.name: c for c in table.columns}
        for raw in rows:
            values = {k: _decode(cols[k], v) for k, v in raw.items() if k in cols}
            res = await db.execute(pg_insert(table).values(**values).on_conflict_do_nothing())
            count += res.rowcount or 0
        inserted[table.name] = count
    return inserted


# --- File helpers ---

def _stamp(now: datetime | None = None) -> str:
    return (now or datetime.now()).strftime("%Y-%m-%d-%H%M%S")


async def export_to_file(db: AsyncSession, path: Path | None = None) -> tuple[Path, dict]:
    snapshot = await export_state(db)
    target = path or (backup_dir() / f"advary-{_stamp()}.json")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(snapshot, ensure_ascii=False, indent=2), encoding="utf-8")
    counts = {name: len(rows) for name, rows in snapshot["tables"].items() if rows}
    return target, counts


def latest_backup() -> Path | None:
    directory = backup_dir()
    if not directory.is_dir():
        return None
    files = sorted(directory.glob("advary-*.json"))
    return files[-1] if files else None


async def import_from_file(db: AsyncSession, path: Path) -> dict[str, int]:
    snapshot = json.loads(path.read_text(encoding="utf-8"))
    result = await import_state(db, snapshot)
    await db.commit()
    return result
