"""Generate the paper's tables and figures from the harness output.

    python paper/build_assets.py

Reads backend/research/generated/results.json (produced by
`docker compose exec api python -m research.make_results`) and writes:

    paper/tables/tab_sms.tex        \\input-ed by expensitor.tex
    paper/tables/tab_receipt.tex
    paper/tables/tab_reasons.tex
    paper/figures/fig_architecture.pdf     (+ .png preview)
    paper/figures/fig_sms_detection.pdf    (+ .png)
    paper/figures/fig_reason_ranking.pdf   (+ .png)

Every number in the tables/figures therefore comes from the code over the
checked-in data — nothing is hand-typed. Re-run whenever the datasets change.

Only dependency beyond the standard library is matplotlib (see
backend/research/requirements-eval.txt).
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch  # noqa: E402

ROOT = Path(__file__).resolve().parent
RESULTS = ROOT.parent / "backend" / "research" / "generated" / "results.json"
TABLES = ROOT / "tables"
FIGURES = ROOT / "figures"

# IEEE-ish look: serif, small, print-safe grayscale with hatching so the figures
# survive black-and-white printing.
plt.rcParams.update({
    "font.family": "serif",
    "font.size": 8,
    "axes.titlesize": 9,
    "axes.labelsize": 8,
    "legend.fontsize": 7,
    "xtick.labelsize": 7.5,
    "ytick.labelsize": 7.5,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "figure.dpi": 200,
})
GRAYS = ["#2b2b2b", "#6f6f6f", "#a6a6a6", "#d0d0d0"]
HATCHES = ["", "///", "...", "xxx"]


def _f3(x: float) -> str:
    return f"{x:.3f}"


# ---------------------------------------------------------------- tables -----
def _bold_col_max(rows: list[list[float]]) -> list[list[bool]]:
    """Mark, per column, the cell(s) holding the column maximum."""
    if not rows:
        return []
    cols = len(rows[0])
    maxes = [max(r[c] for r in rows) for c in range(cols)]
    return [[abs(r[c] - maxes[c]) < 1e-9 for c in range(cols)] for r in rows]


def _cell(val: float, bold: bool) -> str:
    s = _f3(val)
    return f"\\textbf{{{s}}}" if bold else s


def write_sms_table(sms: dict) -> None:
    e = sms["detection"]["expensitor"]
    b = sms["detection"]["baseline"]
    rows = [
        ("Expensitor (rules)", [e["precision"], e["recall"], e["f1"], e["accuracy"]]),
        ("Baseline (any amount)", [b["precision"], b["recall"], b["f1"], b["accuracy"]]),
    ]
    bold = _bold_col_max([r[1] for r in rows])
    body = "\n".join(
        f"{name} & " + " & ".join(_cell(v, bold[i][j]) for j, v in enumerate(vals)) + "\\\\"
        for i, (name, vals) in enumerate(rows)
    )
    tex = f"""% GENERATED by paper/build_assets.py from research/generated/results.json (do not edit).
\\begin{{table}}[t]
\\caption{{Bank-SMS detection (seed set, {sms['n']} messages: {sms['positives']} transactions, {sms['negatives']} non-transactions).}}
\\label{{tab:sms}}
\\centering
\\begin{{tabular}}{{lcccc}}
\\toprule
Method & Precision & Recall & F\\textsubscript{{1}} & Accuracy\\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    (TABLES / "tab_sms.tex").write_text(tex, encoding="utf-8")


def write_receipt_table(r: dict) -> None:
    li = r["line_items"]
    tex = f"""% GENERATED by paper/build_assets.py from research/generated/results.json (do not edit).
\\begin{{table}}[t]
\\caption{{Receipt extraction (seed set, {r['n']} samples, clean text).}}
\\label{{tab:receipt}}
\\centering
\\begin{{tabular}}{{lc}}
\\toprule
Metric & Score\\\\
\\midrule
Receipt detection F\\textsubscript{{1}} & {_f3(r['detection']['f1'])}\\\\
Total exact-match & {_f3(r['total']['exact'])}\\\\
Merchant exact-match & {_f3(r['merchant']['exact'])}\\\\
Line-item F\\textsubscript{{1}} (P {_f3(li['precision'])} / R {_f3(li['recall'])}) & {_f3(li['f1'])}\\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    (TABLES / "tab_receipt.tex").write_text(tex, encoding="utf-8")


def write_reasons_table(r: dict) -> None:
    labels = {
        "Expensitor (amount-aware)": "Expensitor (amount-aware)",
        "most_frequent": "Most-frequent",
        "most_recent": "Most-recent",
        "random": "Random",
    }
    order = ["Expensitor (amount-aware)", "most_frequent", "most_recent", "random"]
    rows = [[r["methods"][k]["hit1"], r["methods"][k]["hit3"], r["methods"][k]["mrr"]] for k in order]
    bold = _bold_col_max(rows)
    body = "\n".join(
        f"{labels[k]} & " + " & ".join(_cell(v, bold[i][j]) for j, v in enumerate(rows[i])) + "\\\\"
        for i, k in enumerate(order)
    )
    tex = f"""% GENERATED by paper/build_assets.py from research/generated/results.json (do not edit).
\\begin{{table}}[t]
\\caption{{Reason-suggestion ranking ({r['probes']} synthetic held-out probes over a {r['history_days']}-day history).}}
\\label{{tab:reasons}}
\\centering
\\begin{{tabular}}{{lccc}}
\\toprule
Method & Hit@1 & Hit@3 & MRR\\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    (TABLES / "tab_reasons.tex").write_text(tex, encoding="utf-8")


# --------------------------------------------------------------- figures -----
def _save(fig, name: str) -> None:
    fig.savefig(FIGURES / f"{name}.pdf", bbox_inches="tight")
    fig.savefig(FIGURES / f"{name}.png", bbox_inches="tight")
    plt.close(fig)


def fig_sms(sms: dict) -> None:
    metrics = ["Precision", "Recall", "F$_1$", "Accuracy"]
    e = sms["detection"]["expensitor"]
    b = sms["detection"]["baseline"]
    exp = [e["precision"], e["recall"], e["f1"], e["accuracy"]]
    base = [b["precision"], b["recall"], b["f1"], b["accuracy"]]

    fig, ax = plt.subplots(figsize=(3.4, 2.1))
    x = range(len(metrics))
    w = 0.38
    ax.bar([i - w / 2 for i in x], exp, w, label="Expensitor (rules)",
           color=GRAYS[0], hatch=HATCHES[0], edgecolor="white")
    ax.bar([i + w / 2 for i in x], base, w, label="Baseline (any amount)",
           color=GRAYS[2], hatch=HATCHES[1], edgecolor="white")
    ax.set_xticks(list(x))
    ax.set_xticklabels(metrics)
    ax.set_ylim(0, 1.08)
    ax.set_ylabel("score")
    ax.legend(frameon=False, loc="lower center", ncol=2, bbox_to_anchor=(0.5, -0.42))
    _save(fig, "fig_sms_detection")


def fig_reasons(reasons: dict) -> None:
    metrics = ["Hit@1", "Hit@3", "MRR"]
    order = ["Expensitor (amount-aware)", "most_frequent", "most_recent", "random"]
    nice = ["Expensitor", "Most-frequent", "Most-recent", "Random"]
    series = [[reasons["methods"][k][m] for m in ("hit1", "hit3", "mrr")] for k in order]

    fig, ax = plt.subplots(figsize=(3.4, 2.2))
    x = range(len(metrics))
    w = 0.2
    for i, (vals, label) in enumerate(zip(series, nice)):
        off = (i - 1.5) * w
        ax.bar([j + off for j in x], vals, w, label=label,
               color=GRAYS[i], hatch=HATCHES[i], edgecolor="white")
    ax.set_xticks(list(x))
    ax.set_xticklabels(metrics)
    ax.set_ylim(0, 0.9)
    ax.set_ylabel("score")
    ax.legend(frameon=False, loc="upper right", ncol=1)
    _save(fig, "fig_reason_ranking")


def fig_architecture() -> None:
    """Hand-laid block diagram of the privacy boundary. No external assets."""
    fig, ax = plt.subplots(figsize=(3.4, 3.35))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 13)
    ax.axis("off")

    def box(x, y, w, h, text, *, dashed=False, fill="#f4f4f4"):
        style = "round,pad=0.02,rounding_size=0.15"
        p = FancyBboxPatch((x, y), w, h, boxstyle=style,
                           linewidth=1.1, edgecolor="#2b2b2b", facecolor=fill,
                           linestyle="--" if dashed else "-")
        ax.add_patch(p)
        ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=7.0)

    def arrow(x1, y1, x2, y2, text=""):
        ax.add_patch(FancyArrowPatch((x1, y1), (x2, y2), arrowstyle="-|>",
                                     mutation_scale=11, linewidth=1.1, color="#2b2b2b"))
        if text:
            ax.text((x1 + x2) / 2 + 0.2, (y1 + y2) / 2, text, ha="left", va="center",
                    fontsize=6.3, style="italic")

    # Device (client) — the trust boundary.
    ax.add_patch(FancyBboxPatch((0.3, 6.9), 9.4, 5.9, boxstyle="round,pad=0.02,rounding_size=0.2",
                                linewidth=1.4, edgecolor="#2b2b2b", facecolor="#ffffff"))
    ax.text(5.0, 12.35, "On device (Flutter client)", ha="center", va="center",
            fontsize=7.6, fontweight="bold")
    box(0.7, 10.1, 4.2, 1.5, "Bank SMS\n(rule-based parse)")
    box(5.1, 10.1, 4.2, 1.5, "Receipt photo →\non-device OCR (ML Kit)")
    box(0.7, 7.4, 4.2, 1.9, "Companion UI\n(one-tap reasons,\nexplainable advice)")
    box(5.1, 7.4, 4.2, 1.9, "Candidate review\n(user confirms;\nnothing auto-saved)")
    arrow(2.8, 10.1, 2.8, 9.3)
    arrow(7.2, 10.1, 7.2, 9.3)

    # Backend.
    ax.add_patch(FancyBboxPatch((0.3, 0.85), 9.4, 5.15, boxstyle="round,pad=0.02,rounding_size=0.2",
                                linewidth=1.4, edgecolor="#2b2b2b", facecolor="#ffffff"))
    ax.text(5.0, 5.62, "Backend (FastAPI) — the user's own data only",
            ha="center", va="center", fontsize=7.6, fontweight="bold")
    box(0.7, 3.15, 4.2, 1.75, "Deterministic engines\n(projection, feasibility,\nbehavioural profile)")
    box(5.1, 3.15, 4.2, 1.75, "Adaptive reason\nranking (per-user)")
    box(0.7, 1.1, 4.2, 1.75, "Per-user store\n(PostgreSQL)")
    box(5.1, 1.1, 4.2, 1.75, "Optional local LLM\n(phrasing only,\nbehind rules fallback)", dashed=True, fill="#ededed")

    arrow(5.0, 6.9, 5.0, 6.0, "confirmed text only")

    ax.text(5.0, 0.5, "No cloud OCR · no 3rd-party txn API · no pooled cross-user model · no paid LLM",
            ha="center", va="center", fontsize=6.3, style="italic")
    _save(fig, "fig_architecture")


def main() -> None:
    if not RESULTS.exists():
        raise SystemExit(
            f"missing {RESULTS}\nRun first:  docker compose exec api python -m research.make_results")
    data = json.loads(RESULTS.read_text(encoding="utf-8"))
    TABLES.mkdir(exist_ok=True)
    FIGURES.mkdir(exist_ok=True)

    write_sms_table(data["sms"])
    write_receipt_table(data["receipts"])
    write_reasons_table(data["reasons"])
    fig_sms(data["sms"])
    fig_reasons(data["reasons"])
    fig_architecture()

    print("wrote:")
    for p in sorted(list(TABLES.glob('*.tex')) + list(FIGURES.glob('*.pdf'))):
        print(f"  {p.relative_to(ROOT.parent)}")


if __name__ == "__main__":
    main()
